version: '3.4'

services:
  postgres:
    container_name: postgres
    image: postgis/postgis:12-3.0-alpine

  hasura:
    container_name: hasura
    image: hasura/graphql-engine:v1.3.0
    depends_on:
      - postgres
